sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
linkReplacements:
  - "https://github.com/exasol/test-db-builder|https://github.com/exasol/test-db-builder-java"
  - "https://github.com/exasol/udf-debugging-javat|https://github.com/exasol/udf-debugging-java"
