community-tags:
  - DB2
  - Virtual Schema
  - Open Source
  - GitHub
community-project-name: DB2 Virtual Schema
community-project-description: |
  The **DB2 Virtual Schema** provides an abstraction layer that makes an external [DB2](https://www.ibm.com/db2/)
  accessible from an Exasol database through regular SQL commands.
  The contents of the external DB2 database are mapped to virtual tables which
  look like and can be queried as any regular Exasol table.
release-platforms:
  - GitHub
  - Community
  - Jira